### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by laurabuggiotti** [fischuu/hoardeR#5] opened 2018-01-31 16:22 UTC
Hi,

Im trying to install hoardeR as i would like to use subPhased, but complains that is not available (for R version 3.4), i have tried with 3.2.5 but get the same problem.
Would you be so kind to help me with this issue?

Thanks a lot,
Laura

**Comment by fischuu** [comment] 2018-01-31 17:18
Hi Laura,

sure, apparently you are trying to install hoardeR with an older R version, which results in some problems. However, unfortunately there are currently quite many dependencies in the package so that the installation might cause some problems anyway.

But what you can do, if you only aim for the subPhased() function, you can just source this function here from the github repository:

source("https://raw.githubusercontent.com/fischuu/hoardeR/master/R/subPhased.R")

there shouldn't be any further dependencies. After you have sourced that function it will be available for this session. If you need the fixed version of the function I would recommend to download the file instead, store it locally and then source it from your HDD.

 Please let me know if this solves your issue or if you need any further help with it.

**Comment by laurabuggiotti** [comment] 2018-02-01 10:48
Thanks for your prompt answer!

Indeed the dependencies were mainly the problem, anyway I have now sourced
the function.

I used the following command to run it:
subPhased(file="phased_file", vmmk = "Chr1-Variant-Map-Master-Key.txt",
out="out_prova", chunkSize=100000, verbose=TRUE, removeInsertions=TRUE)

but got the following message:
I read the master key file Thu Feb  1 10:41:57 2018
Error in 1:nchunks : argomento NA/NaN

do you reckon is something wrong with my file?

Thanks a lot for your help,
Laura

2018-01-31 17:18 GMT+00:00 Daniel Fischer <notifications@github.com>:

**Comment by fischuu** [comment] 2018-02-01 11:18
I just checked the code (I wrote it quite a while ago...), and I noticed that some of the codes are only work under Linux OS, so I would actually improve the function. Do you run it on Windows? I could prepare an OS safe version of it, but cannot do it today anymore (maybe in the evening, lets see).

I assume the issue is that I used back then a system command to determine the number of rows in the file, which is of course not the best way to do and should be fixed. Nowadays I would use the data.table package instead, I'll try to rewrite this part.

But if you know the number of lines inside your phased file, I could send you a quick fix...

Best wishes
 Daniel

**Comment by laurabuggiotti** [comment] 2018-02-01 11:24
im running it on OS (my macbook pro) but i could try to source the function
in my user's environment of a cluster i have access to which has Linux.
The number of lines are going to be different as i have phased genotypes by
chromosomes (e-g chr1 number of lines 121819).

Thanks,
Laura

2018-02-01 11:18 GMT+00:00 Daniel Fischer <notifications@github.com>:

**Comment by fischuu** [comment] 2018-02-01 11:34
I just changed the part that determines the number of lines, maybe that helps to run the function, though it might be slow. I really should change that function to use the data table package, I try to do that asap, but currently I do not have test data with me, so it might take until Monday...

In the meanwhile, you could try to source this fix here:

source("https://raw.githubusercontent.com/fischuu/hoardeR/master/R/subPhased_uglyFix.R")

**Comment by laurabuggiotti** [comment] 2018-02-01 11:35
Hi Daniel,

it works fine in the cluster!

Thanks a lot for your help,
Laura

2018-02-01 11:24 GMT+00:00 laura buggiotti <laurabuggiotti@gmail.com>:

**Comment by fischuu** [comment] 2018-02-01 11:36
Okay, perfect! Hopefully it will serve you well then!

but for future reference I should really change it to get it OS independent...

Best wishes,
 Daniel

**Closed as completed** 2018-02-02 18:16 UTC
